### ISSUE TITLE
Slight differences for cases with missing alues

### ISSUE THREAD

**Issue by CarlosLopezVazquezUY** [jmgirard/mReliability#6]
Hello:
Thank you for your toolbox. I am checking some results of mALPHAK against those published by Prof. Krippendorf at http://repository.upenn.edu/asc_papers/43. I found some issues only for cases with missing values.

A) Binary or dichotomous data, two observers, no missing data
SS=[0 1 0 0 0 0 0 0 1 0;1 1 1 0 0 1 0 0 0 0];
mALPHAK(SS',[0 1],'identity') results in 0.0952 which agrees with reported value

B) Nominal data, two observers, no missing data
SS=[1 1 2 2 4 3 3 3 5 4 4 1;2 1 2 2 2 3 3 3 5 4 4 4];
mALPHAK(SS',[1:5],'identity') results in 0.692 which agrees with reported value

C) Nominal data, any number of observers, missing data
     SS=[ 1 2 3 3 2 1 4 1 2 NaN NaN NaN; 1 2 3 3 2 2 4 1 2 5 NaN 3;NaN 3 3 3 2 3 4 2 2 5 1 NaN;1 2 3 3 2 4 4 1 2 5 1 NaN];
     mALPHAK(SS',[1:5],'identity') results in 0.7453 while in the paper is 0.743=904/1216

The rational number is what Prof. Krippendorf computes, so it is exact. Have you noticed problems like this in the code? Maybe is my mistake: I changed the NaN for Inf just to be shure that makes no difference.
Thank you a lot for your interest.
Carlos, from Uruguay, South America

**Comment by jmgirard** [comment]
Hi Carlos,
Thanks for your attention to detail. There was a slight bug on line 86. It should be fixed now.

**Comment by CarlosLopezVazquezUY** [comment]
Thank you a lot for your quick answer. I'll give it a try and let you know.
Regards
Carlos
