### ISSUE TITLE
Datatype assertion in weight matrix generation

### ISSUE THREAD

**Issue by bmaneesh** [jmgirard/mReliability#7]
Firstly, thank you for making the implementations opensource and also for the wiki on them.

`mWEIGHTING.m` when creating the linear weight matrix, the `dist/maxdist` division returns rounded-off int weight matrix for int categories. This leads to inflated scores. I think a datatype check could be incorporated to convert the categories or codes to double. This is just a corner case but it does not raise any flags unless inspected in depth. I think the same is valid for quadratic weighting as well.

**Comment by jmgirard** [comment]
Thanks for this.
